// Identify the Leanback client as the native Xbox YouTube-TV Cobalt shell.
// The UWP host applies the same Cobalt UA to documents, requests, service workers
// and Google/YouTube account pages. Authentication tokens, visitor data, cookies,
// delegated sessions and account IDs are deliberately left untouched.
const packageInfo = require('../../xbox/app-info.json')
const xhrModifiers = require('../util/xhrModifiers')
const configOverrides = require('../util/configOverrides')
const functions = require('../util/functions')

const platform = window.__VACUUMTUBE_PLATFORM__ || {}
const deviceModel = platform.userAgentModel || platform.model || 'Xbox Series X'
const osVersion = platform.osVersion || '10.0'
const cobaltVersion = platform.cobaltVersion || '25.lts.40.1035033'
const releaseVehicle = platform.cobaltReleaseVehicle || 'gold'
const starboardVersion = platform.starboardVersion || '15'

const identity = {
    platform: 'GAME_CONSOLE',
    platformDetail: 'XBOX',
    clientFormFactor: 'LARGE_FORM_FACTOR',
    deviceMake: 'Microsoft',
    deviceModel,
    browserName: 'Cobalt',
    browserVersion: cobaltVersion,
    osName: 'Xbox',
    osVersion,
    tvAppInfo: { releaseVehicle }
}

const playerDevice = {
    platform: 'GAME_CONSOLE',
    platformDetail: 'XBOX',
    brand: 'Microsoft',
    model: deviceModel,
    browser: 'Cobalt',
    browserVersion: cobaltVersion,
    os: 'Xbox',
    osVersion,
    cobaltReleaseVehicle: releaseVehicle
}

module.exports = () => {
    configOverrides.environmentOverrides.push({
        platform: 'GAME_CONSOLE',
        platform_detail: 'XBOX',
        brand: 'Microsoft',
        model: deviceModel,
        engine: 'Cobalt',
        browser_engine: 'Cobalt',
        browser_engine_version: cobaltVersion,
        browser: 'Cobalt',
        browser_version: cobaltVersion,
        os: 'Xbox',
        os_version: osVersion,
        feature_switches: {
            mdx_device_label: `VacuumTube ${packageInfo.version} on ${platform.deviceName || deviceModel}`,
            starboard_api_version: starboardVersion
        }
    })

    configOverrides.ytcfgOverrides.push({
        INNERTUBE_CONTEXT: { client: identity },
        WEB_PLAYER_CONTEXT_CONFIGS: {
            WEB_PLAYER_CONTEXT_CONFIG_ID_LIVING_ROOM_WATCH: {
                device: playerDevice
            }
        }
    })

    // Some requests are created before all config overrides have propagated.
    // Patch only the Xbox/Cobalt device identity. Account and session data stays
    // exactly as generated by YouTube and the persistent WebView2 profile.
    xhrModifiers.addRequestModifier((url, body) => {
        if (!String(url).includes('/youtubei/')) return body
        let json
        try { json = JSON.parse(body) } catch { return body }
        if (json?.context?.client) {
            functions.deepMerge(json.context.client, identity)
            body = JSON.stringify(json)
        }
        return body
    })

    xhrModifiers.addResponseModifier((url, text) => {
        if (!String(url).includes('/tv_config')) return
        try {
            const parts = text.split('\n')
            const index = parts.length - 1
            const json = JSON.parse(parts[index])
            const device = json?.webPlayerContextConfig?.WEB_PLAYER_CONTEXT_CONFIG_ID_LIVING_ROOM_WATCH?.device
            if (device) {
                functions.deepMerge(device, playerDevice)
                parts[index] = JSON.stringify(json)
                return parts.join('\n')
            }
        } catch (error) {
            console.warn('[Identification] Failed to patch tv_config', error)
        }
    })
}
